---
- name: Reload the sysctl configuration
  # We have to use the command here because (to date) the
  # ansible.posix.sysctl module does not allow to force a reload
  ansible.builtin.command:
    cmd: sysctl --system
  when: reload_sysctl_if_changed
